apiVersion: v1
kind: Service
metadata:
  labels:
    cloudzcp.io/realm: tworld
    cloudzcp.io/project: tworld-biz
    cloudzcp.io/zcpapplication: testmaven
  name: testmaven
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    cloudzcp.io/realm: tworld
    cloudzcp.io/project: tworld-biz
    cloudzcp.io/zcpapplication: testmaven
  type: ClusterIP
